import type { Project, Task } from '../types';

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'E-Commerce Platform',
    description: 'Full-stack online store with React & Node.js',
    color: '#6366f1',
    icon: '🛒',
    createdAt: '2024-11-01T00:00:00Z',
    taskCount: 8,
  },
  {
    id: 'p2',
    name: 'Mobile App Redesign',
    description: 'UI/UX overhaul for the mobile application',
    color: '#ec4899',
    icon: '📱',
    createdAt: '2024-11-10T00:00:00Z',
    taskCount: 5,
  },
  {
    id: 'p3',
    name: 'API Gateway',
    description: 'Microservices API layer with rate limiting',
    color: '#22c55e',
    icon: '🌐',
    createdAt: '2024-12-01T00:00:00Z',
    taskCount: 6,
  },
];

export const SAMPLE_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Set up React 19 project with TypeScript',
    description: 'Initialize the project with Vite, configure Tailwind CSS, set up ESLint and Prettier for code quality.',
    status: 'done',
    priority: 'high',
    labels: [{ id: 'l5', name: 'Frontend', color: '#06b6d4' }],
    assignee: 'Nilesh',
    dueDate: '2024-11-15T00:00:00Z',
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-14T00:00:00Z',
    projectId: 'p1',
    subtasks: [
      { id: 's1', title: 'Configure Vite + React 19', completed: true },
      { id: 's2', title: 'Set up Tailwind v3', completed: true },
      { id: 's3', title: 'Configure path aliases', completed: true },
    ],
    comments: [
      {
        id: 'c1',
        author: 'Nilesh',
        content: 'Used Vite 6 with the latest React 19 RC. Everything working smoothly.',
        createdAt: '2024-11-14T10:00:00Z',
      },
    ],
  },
  {
    id: 't2',
    title: 'Build product listing page with filters',
    description: 'Create a responsive product grid with search, category filter, price range filter, and sort options.',
    status: 'done',
    priority: 'high',
    labels: [
      { id: 'l5', name: 'Frontend', color: '#06b6d4' },
      { id: 'l2', name: 'Feature', color: '#6366f1' },
    ],
    assignee: 'Priya',
    dueDate: '2024-11-25T00:00:00Z',
    createdAt: '2024-11-05T00:00:00Z',
    updatedAt: '2024-11-24T00:00:00Z',
    projectId: 'p1',
    subtasks: [
      { id: 's4', title: 'Product card component', completed: true },
      { id: 's5', title: 'Filter sidebar', completed: true },
      { id: 's6', title: 'Pagination', completed: true },
    ],
    comments: [],
  },
  {
    id: 't3',
    title: 'Implement shopping cart with Zustand',
    description: 'Global cart state management with add/remove/update quantity, persisted to localStorage.',
    status: 'in-progress',
    priority: 'high',
    labels: [
      { id: 'l5', name: 'Frontend', color: '#06b6d4' },
      { id: 'l2', name: 'Feature', color: '#6366f1' },
    ],
    assignee: 'Nilesh',
    dueDate: '2024-12-10T00:00:00Z',
    createdAt: '2024-11-20T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    projectId: 'p1',
    subtasks: [
      { id: 's7', title: 'Cart store with Zustand', completed: true },
      { id: 's8', title: 'Cart sidebar UI', completed: true },
      { id: 's9', title: 'Persist to localStorage', completed: false },
      { id: 's10', title: 'Cart item quantity controls', completed: false },
    ],
    comments: [
      {
        id: 'c2',
        author: 'Rahul',
        content: 'Should we use Zustand persist middleware here?',
        createdAt: '2024-11-22T14:00:00Z',
      },
      {
        id: 'c3',
        author: 'Nilesh',
        content: 'Yes, already planned. Will implement in the next sub-task.',
        createdAt: '2024-11-22T14:30:00Z',
      },
    ],
  },
  {
    id: 't4',
    title: 'User authentication with JWT',
    description: 'Login/register flow, JWT token management, protected routes, refresh token logic.',
    status: 'in-progress',
    priority: 'urgent',
    labels: [{ id: 'l4', name: 'Backend', color: '#f97316' }],
    assignee: 'Rahul',
    dueDate: '2024-12-05T00:00:00Z',
    createdAt: '2024-11-15T00:00:00Z',
    updatedAt: '2024-11-30T00:00:00Z',
    projectId: 'p1',
    subtasks: [
      { id: 's11', title: 'Login API integration', completed: true },
      { id: 's12', title: 'JWT interceptor for Axios', completed: false },
      { id: 's13', title: 'Protected route HOC', completed: false },
    ],
    comments: [],
  },
  {
    id: 't5',
    title: 'Payment gateway integration',
    description: 'Integrate Razorpay for Indian market, handle success/failure webhooks, order confirmation emails.',
    status: 'todo',
    priority: 'high',
    labels: [
      { id: 'l4', name: 'Backend', color: '#f97316' },
      { id: 'l2', name: 'Feature', color: '#6366f1' },
    ],
    assignee: 'Nilesh',
    dueDate: '2024-12-20T00:00:00Z',
    createdAt: '2024-11-20T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
    projectId: 'p1',
    subtasks: [],
    comments: [],
  },
  {
    id: 't6',
    title: 'Admin dashboard with analytics',
    description: 'Sales overview, inventory management, order processing panel with charts using Recharts.',
    status: 'todo',
    priority: 'medium',
    labels: [
      { id: 'l5', name: 'Frontend', color: '#06b6d4' },
      { id: 'l2', name: 'Feature', color: '#6366f1' },
    ],
    assignee: 'Sneha',
    dueDate: '2025-01-10T00:00:00Z',
    createdAt: '2024-11-25T00:00:00Z',
    updatedAt: '2024-11-25T00:00:00Z',
    projectId: 'p1',
    subtasks: [],
    comments: [],
  },
  {
    id: 't7',
    title: 'Fix cart total calculation bug',
    description: 'When applying coupon codes, the total is not updating correctly after item quantity change.',
    status: 'review',
    priority: 'urgent',
    labels: [{ id: 'l1', name: 'Bug', color: '#ef4444' }],
    assignee: 'Nilesh',
    dueDate: '2024-12-03T00:00:00Z',
    createdAt: '2024-11-28T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    projectId: 'p1',
    subtasks: [
      { id: 's14', title: 'Reproduce the bug', completed: true },
      { id: 's15', title: 'Write unit test', completed: true },
      { id: 's16', title: 'Apply fix', completed: true },
    ],
    comments: [
      {
        id: 'c4',
        author: 'Priya',
        content: 'Found the issue — coupon discount was applied before tax calculation.',
        createdAt: '2024-11-30T09:00:00Z',
      },
    ],
  },
  {
    id: 't8',
    title: 'Write API documentation',
    description: 'Document all REST endpoints using Swagger/OpenAPI 3.0 spec with example requests and responses.',
    status: 'todo',
    priority: 'low',
    labels: [{ id: 'l6', name: 'Docs', color: '#22c55e' }],
    assignee: 'Amit',
    dueDate: '2025-01-15T00:00:00Z',
    createdAt: '2024-12-01T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    projectId: 'p1',
    subtasks: [],
    comments: [],
  },
  // Project 2 tasks
  {
    id: 't9',
    title: 'Design new navigation system',
    description: 'Bottom tab bar redesign with smoother transitions and better iconography for mobile.',
    status: 'in-progress',
    priority: 'high',
    labels: [{ id: 'l3', name: 'Design', color: '#ec4899' }],
    assignee: 'Sneha',
    dueDate: '2024-12-15T00:00:00Z',
    createdAt: '2024-11-15T00:00:00Z',
    updatedAt: '2024-11-29T00:00:00Z',
    projectId: 'p2',
    subtasks: [
      { id: 's17', title: 'Figma wireframes', completed: true },
      { id: 's18', title: 'Component implementation', completed: false },
    ],
    comments: [],
  },
  {
    id: 't10',
    title: 'Improve onboarding flow',
    description: 'Reduce drop-off with a 3-step guided onboarding experience with skip option.',
    status: 'todo',
    priority: 'medium',
    labels: [
      { id: 'l3', name: 'Design', color: '#ec4899' },
      { id: 'l2', name: 'Feature', color: '#6366f1' },
    ],
    assignee: 'Nilesh',
    dueDate: '2024-12-28T00:00:00Z',
    createdAt: '2024-11-20T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
    projectId: 'p2',
    subtasks: [],
    comments: [],
  },
  // Project 3 tasks
  {
    id: 't11',
    title: 'Set up Kong API Gateway',
    description: 'Configure Kong with rate limiting, API key auth, and logging plugins.',
    status: 'done',
    priority: 'high',
    labels: [{ id: 'l4', name: 'Backend', color: '#f97316' }],
    assignee: 'Rahul',
    dueDate: '2024-11-20T00:00:00Z',
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-18T00:00:00Z',
    projectId: 'p3',
    subtasks: [
      { id: 's19', title: 'Docker setup', completed: true },
      { id: 's20', title: 'Rate limit plugin', completed: true },
    ],
    comments: [],
  },
  {
    id: 't12',
    title: 'Implement request caching layer',
    description: 'Redis-based caching for frequent API calls with configurable TTL per endpoint.',
    status: 'in-progress',
    priority: 'medium',
    labels: [{ id: 'l4', name: 'Backend', color: '#f97316' }],
    assignee: 'Amit',
    dueDate: '2024-12-15T00:00:00Z',
    createdAt: '2024-11-10T00:00:00Z',
    updatedAt: '2024-11-28T00:00:00Z',
    projectId: 'p3',
    subtasks: [
      { id: 's21', title: 'Redis connection setup', completed: true },
      { id: 's22', title: 'Cache middleware', completed: false },
    ],
    comments: [],
  },
];
